# CircleCI v2 Config
version: 2

defaults: &defaults
  working_directory: /home/circleci/project
  docker:
    - image: circleci/node:8.9.4

defaults_npm_auth: &defaults_npm_auth
  - run:
      name: Update NPM registry auth token
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  
defaults_npm_publish: &defaults_npm_publish
  - run:
      name: Publish NPM $CIRCLE_TAG artifact
      command: npm publish --tag $CIRCLE_TAG --access public
  - run:
      name: Publish NPM $RELEASE_TAG artifact
      command: npm publish --tag $RELEASE_TAG --access public

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update NPM install
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  
  test-unit:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Create dir for test results
          command: mkdir -p ./test/results
      - run:
          name: Execute unit tests
          command: npm -s run test:xunit > ./test/results/tape.xml
      - store_artifacts:
          path: ./test/results
          prefix: test
      - store_test_results:
          path: ./test/results
  
  test-coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Execute code coverage check
          command: npm -s run test:coverage-check
      - store_artifacts:
          path: coverage
          prefix: test
      - store_test_results:
          path: coverage/lcov.info
  
  deploy-snapshot:
    <<: *defaults
    steps:
      - run:
          name: setup environment vars for SNAPSHOT release
          command: |
            echo 'export RELEASE_TAG=$RELEASE_TAG_SNAPSHOT' >> $BASH_ENV
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      <<: *defaults_npm_auth
      <<: *defaults_npm_publish
  
  deploy:
    <<: *defaults 
    steps:
      - run:
          name: setup environment vars for SNAPSHOT release
          command: |
            echo 'export RELEASE_TAG=$RELEASE_TAG' >> $BASH_ENV
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      <<: *defaults_npm_auth
      <<: *defaults_npm_publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup:
          context: org-global
          filters:
            tags:
              only: /.*/
            branches:
              ignore: 
                - /feature*/
                - /bugfix*/
      - test-unit:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore: 
                - /feature*/
                - /bugfix*/
      - test-coverage:
          context: org-global
          requires:
            - setup
          filters:
            tags:
              only: /.*/
            branches:
              ignore: 
                - /feature*/
                - /bugfix*/
      - deploy-snapshot:
          context: org-global
          requires:
            - setup
            - test-unit
            - test-coverage
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*\-snapshot/
            branches:
              ignore: 
                - /.*/
      - deploy:
          context: org-global
          requires:
            - setup
            - test-unit
            - test-coverage
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: 
                - /.*/
